name: Pulumi Deploy

on:
  push:
    branches:
      - pulumi-infra
  pull_request:
    branches:
      - pulumi-infra
  workflow_dispatch:

jobs:
  # vault-secret:
  #   runs-on: ubuntu-latest
  #   steps:
      # - name: Install Vault CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y vault
      
      # - name: Retrieve AWS credentials from Vault
      #   id: vault
      #   env:
      #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      #     VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      #   run: |
      #     AWS_CREDS=$(vault kv get -format=json secret/aws | jq -r '.data.data.creds')
      #     echo "AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r '.aws_access_key_id')" >> $GITHUB_ENV
      #     echo "AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.aws_secret_access_key')" >> $GITHUB_ENV

  pulumi:
    env:
      INFRA_DESTROY : ${{vars.INFRA_DESTROY || 'false'}}
    # needs: vault-secret
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if using Pulumi with Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18    

      # Step 3: Install Pulumi CLI
      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH
          echo "$INFRA_DESTROY"

      # Step 4: Configure AWS credentials (if using AWS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Login to Pulumi
      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Step 6: Install dependencies (if using Node.js)
      - name: Install dependencies
        run: npm install

      # Step 7: Run Pulumi Up (provision)
      - name: Pulumi Up
        if: vars.INFRA_DESTROY == 'false'
        run: pulumi up --stack dev --yes

     # Step 8: Run Pulumi Down (Deprovision)
      - name: Pulumi Down
        if: vars.INFRA_DESTROY == 'false'
        run: pulumi down --stack dev --yes